<?php
require_once(__DIR__.'/common.php');
require_once(__DIR__.'/DBStructure.php');


// コンフィグ読み込み
$config = json_decode(file_get_contents(__DIR__."/config.json"));


// DBの情報を取得
list($dbInfo, $structuresPerTable, $foreignKeysPerTable) = DBStructure::load($config->db->host, $config->db->name, $config->db->user, $config->db->pass);

// html生成を開始
$html = '<div id="table_sections">';

// 最初はDB情報
$html .= "<div class=\"table-section\" id=\"database_info\">\n";
$html .= "<h1>".h($config->db->name)."</h1>\n";
$html .= "<h2>DB情報</h2>\n";
$html .= "<table>\n";
$html .= "<tbody>\n";
foreach ($dbInfo[0] as $key => $value) {
    $html .= "<tr>\n";
    $html .= "<th>".h($key)."</th><td>".h($value)."</td>\n";
    $html .= "</tr>\n";
}
$html .= "<tr>\n";
$html .= "<th>テーブル数</th><td>".count($structuresPerTable)."</td>\n";
$html .= "</tr>\n";
$html .= "</tbody>\n";
$html .= "</table>\n";
$html .= "</div>\n";

// テーブル毎の情報
foreach ($structuresPerTable as $tableName => $structures) {
    $html .= "<div style=\"display:none;\" class=\"table-section\" id=\"table_".h($tableName)."\">\n";

    // テーブル名
    $html .= "<h1>".h($config->db->name)." ＞ ".h($tableName)."</h1>\n";

    // テーブルコメント
    $tableComment = $structures['TABLE_STATUS'][0]['Comment'] ?? '';
    if ($tableComment) {
        $html .= "<div class=\"table-comment\">".h($tableComment)."</div>\n";
    }

    // カラム情報
    $html .= "<h2>カラム情報</h2>\n";
    $html .= "<table>\n";
    $html .= "<thead>\n";
    $html .= "<tr>\n";
    foreach (array_keys($structures['TABLE_COLUMNS'][0]) as $tableColumnLabel) {
        $html .= "<th>".h($tableColumnLabel)."</th>\n";
    }
    $html .= "</tr>\n";
    $html .= "</thead>\n";
    $html .= "<tbody>\n";
    foreach ($structures['TABLE_COLUMNS'] as $tableColumns) {
        $html .= "<tr>\n";
        foreach ($tableColumns as $value) {
            $html .= "<td>".h($value)."</td>\n";
        }
        $html .= "</tr>\n";
    }
    $html .= "</tbody>\n";
    $html .= "</table>\n";

    // キー情報
    $html .= "<h2>キー情報</h2>\n";
    $html .= "<table>\n";
    $html .= "<thead>\n";
    $html .= "<tr>\n";
    foreach (array_keys($structures['TABLE_KEYS'][0]) as $tableColumnLabel) {
        $html .= "<th>".h($tableColumnLabel)."</th>\n";
    }
    $html .= "</tr>\n";
    $html .= "</thead>\n";
    $html .= "<tbody>\n";
    foreach ($structures['TABLE_KEYS'] as $tableColumns) {
        $html .= "<tr>\n";
        foreach ($tableColumns as $value) {
            $html .= "<td>".h($value)."</td>\n";
        }
        $html .= "</tr>\n";
    }
    $html .= "</tbody>\n";
    $html .= "</table>\n";

    // 参照制約
    $html .= "<h2>外部キー</h2>\n";
    $html .= "<table>\n";
    $html .= "<thead>\n";
    $html .= "<tr>\n";
    $html .= "<th>Column_name</th>\n";
    $html .= "<th>Referenced_table_name</th>\n";
    $html .= "<th>Referenced_column_name</th>\n";
    $html .= "</tr>\n";
    $html .= "</thead>\n";
    $html .= "<tbody>\n";
    foreach (($foreignKeysPerTable[$tableName] ?? []) as $foreignKeys) {
        $html .= "<tr>\n";
        $html .= "<td>".h($foreignKeys['COLUMN_NAME'])."</td>\n";
        $html .= "<td>".h($foreignKeys['REFERENCED_TABLE_NAME'])."</td>\n";
        $html .= "<td>".h($foreignKeys['REFERENCED_COLUMN_NAME'])."</td>\n";
        $html .= "</tr>\n";
    }
    $html .= "</tbody>\n";
    $html .= "</table>\n";

    // テーブル情報
    $html .= "<h2>テーブル情報</h2>\n";
    $html .= "<table>\n";
    $html .= "<tbody>\n";
    foreach ($structures['TABLE_STATUS'][0] as $key => $value) {
        $html .= "<tr>\n";
        $html .= "<th>".h($key)."</th><td>".h($value)."</td>\n";
        $html .= "</tr>\n";
    }
    $html .= "</tbody>\n";
    $html .= "</table>\n";

    $html .= "</div>\n";
}
$html .= '</div>';


// メニューを表示
$menus = '<div id="menus">';
$menus .= '<strong>DB</strong><br>';
$menus .= '<button type="button" onclick="refreshTableSection(\'database_info\');">'.h($config->db->name).'</button><br>';

$menus .= '<strong>Tables</strong><br>';
foreach ($structuresPerTable as $tableName => $structures) {
    $menus .= '<button type="button" onclick="refreshTableSection(\'table_'.h($tableName).'\');">'.h($tableName).'</button><br>';
}
$menus .= '<div class="copyright">Generated By QuicktDBTeigi.</div>';
$menus .= '</div>';


// htmlの最終調整
$html = '<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * { box-sizing: border-box; }
        html,body { margin:0; padding:0; font-size: 16px; color: #222; }
        body { padding: 10px 15px; }
        h1 { font-size: 20px; }
        h2 { font-size: 18px; }
        button { margin: 2px 0; padding: 4px 6px; background-color: transparent; border: solid 0px #ccc; cursor:pointer; }
        table,th,td { border-collapse: collapse; border:1px solid #666; font-size: 13px; }
        th,td { padding: 5px 8px; /* word-wrap: break-word; white-space: normal; word-break: break-word; */ }
        th { background-color: #eee; }
        #menus { padding: 10px; position: fixed; left:0; top:0; width: 240px; height: 100vh; overflow: scroll; background-color: #f2f2f2; }
        #table_sections { padding-left: 240px; padding-bottom: 40px; }
        .table-comment { padding: 10px; border: solid 1px #ccc; }
        .copyright { margin-top: 10px; padding-top: 8px; text-align: center; font-size: 10px; border-top: solid 1px #ccc; color: #666; }
    </style>
</head>
<body>
' . $menus .'
' . $html . '
</body>
<script>
function refreshTableSection(targetId) {
    document.querySelectorAll(".table-section").forEach(function(value) {
        value.style.display = "none";
    });
    document.getElementById(targetId).style.display = "";
}
</script>
</html>';


// html出力
file_put_contents('db_teigi.html', $html);
